contact_homepage:
    path:     /
    defaults: { _controller: ContactBundle:Default:index }
#Connexion
contact_login:
    path: /connexion
    defaults: { _controller: ContactBundle:Connect:login }

contact_login_check:
    path: /login-check
    defaults: { _controller: ContactBundle:Connect:check }
    requirements:
        _method: POST
        
contact_logout:
    path: /deconnexion
    defaults: { _controller: FOSUserBundle:Security:logout }
    
#Profil utilisateur
fos_user_profile_show:
    pattern: /profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    requirements:
        _method: GET