contact_homepage:
    path:     /
    defaults: { _controller: ContactBundle:Default:index }

contact_login:
    path: /login
    defaults: { _controller: ContactBundle:Connect:login }

contact_login_check:
    path: /login-check
    defaults: { _controller: ContactBundle:Connect:check }
    requirements:
        _method: POST
        
contact_logout:
    path: /logout
    defaults: { _controller: ContactBundle:Connect:logout }