contact_homepage:
    path:     /
    defaults: { _controller: ContactBundle:Default:index }
#Connexion
contact_login:
    path: /connexion
    defaults: { _controller: ContactBundle:Connect:login }

contact_login_check:
    path: /login-check
    defaults: { _controller: ContactBundle:Connect:check }
    requirements:
        _method: POST
        
contact_logout:
    path: /deconnexion
    defaults: { _controller: FOSUserBundle:Security:logout }

contact_add:
    path: /ajout
    defaults: { _controller: ContactBundle:Contact:add }

contact_delete:
    path: /suppr/{id}
    defaults: { _controller: ContactBundle:Contact:suppr }
    methods: GET
    requirements:
        id: \d+
        
contact_mod:
    path: /{id}/modifier
    defaults: { _controller: ContactBundle:Contact:modif }
    methods: [GET, POST]
    requirements:
        id: \d+