services:
    contact_add.form.type:
        class: ContactBundle\Form\ContactFormType
        tags:
            - { name: form.type, alias: contact_form_type}
#   arguments: ["@service_id", "plain_value", %parameter%]
